version: '3'

services:
  search:
    image: getmeili/meilisearch:v1.0
    container_name: search
    restart: unless-stopped
    environment:
      - "MEILI_MASTER_KEY=${MEILI_MASTER_KEY}"
    ports:
      - 7700:7700
    volumes:
      - ./meili_data:/meili_data
